CREATE SCHEMA IF NOT EXISTS portal_seguranca;

DROP ROLE IF EXISTS gt4w_db;

CREATE ROLE gt4w_db LOGIN
  ENCRYPTED PASSWORD 'gt4w_db'
  NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

ALTER ROLE gt4w_db
  SET search_path = gt4w_db, public;
